name: Allure Tests with Full History

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target test
        required: true
        type: choice
        options:
          - first_test
          - second_test

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Устанавливаем Python и зависимости
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest

      # 3️⃣ Подгружаем историю Allure из ветки gh_pages
      - name: Load previous Allure history
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: gh_pages
          path: gh-pages

      # Создаем папку истории для текущих результатов
      - name: Prepare Allure history
        run: |
          mkdir -p allure-results/history
          if [ -d "gh-pages/history" ]; then
            cp -r gh-pages/history/* allure-results/history/
          fi

      # 4️⃣ Запускаем тесты
      - name: Run first_test
        if: "github.event.inputs.deployment_target == 'first_test'"
        run: pytest tests/test_all.py::test_get_all_objects --alluredir=allure-results
        continue-on-error: true
      - name: Run second_test
        if: "github.event.inputs.deployment_target == 'second_test'"
        run: pytest tests/test_all.py::test_get_by_id --alluredir=allure-results
        continue-on-error: true

      # 5️⃣ Генерируем Allure HTML отчет
      - name: Install Allure
        run: |
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.23.1/allure-2.23.1.tgz
          sudo tar -zxvf allure-2.23.1.tgz -C /opt/
          sudo ln -s /opt/allure-2.23.1/bin/allure /usr/bin/allure
      - name: Generate Allure report
        run: allure generate allure-results -o allure-report --clean

      # 6️⃣ Копируем историю в папку для публикации
      - name: Copy history for next runs
        run: |
          mkdir -p allure-report/history
          if [ -d "allure-results/history" ]; then
            cp -r allure-results/history/* allure-report/history/
          fi

      # 7️⃣ Публикуем на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_branch: gh_pages
          publish_dir: allure-report
