name: Automated Allure Tests with History

on:
  workflow_dispatch:
    inputs:
      target:
        description: Choose which tests to run
        required: true
        default: second_test
        type: choice
        options:
          - first_test
          - second_test

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Проверяем код
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3️⃣ Устанавливаем зависимости
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest

      # 4️⃣ Загружаем историю предыдущих отчётов (ветка gh-pages)
      - name: Load previous Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # 5️⃣ Запускаем тесты
      - name: first_test
        if: "github.event.inputs.deployment_target == 'first_test'"
        run: pytest tests/test_all.py::test_get_all_objects --alluredir allure-results
        #     continue-on-error: true
      - name: second_test
        if: "github.event.inputs.deployment_target == 'second_test'"
        run: pytest tests/test_all.py::test_get_by_id --alluredir allure-results
        #        continue-on-error: true

      # 6️⃣ Собираем Allure отчёт с учётом истории
      - name: Build Allure report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages           # где история
          allure_results: allure-results
          allure_history: allure-history

      # 7️⃣ Публикуем отчёт в ветку gh-pages (GitHub Pages)
      - name: Publish Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
