name: Automated Allure Tests with History

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - first_test
          - second_test

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Проверяем код
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3️⃣ Устанавливаем зависимости
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest

      # 4️⃣ Загружаем историю предыдущих отчётов (ветка gh-pages)
      - name: Load previous Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh_pages
          path: gh_pages

      # 5️⃣ Запускаем тесты
      - name: first_test
        if: "github.event.inputs.deployment_target == 'first_test'"
        run: pytest tests/test_all.py::test_get_all_objects --alluredir allure-results
        continue-on-error: true
      - name: second_test
        if: "github.event.inputs.deployment_target == 'second_test'"
        run: pytest tests/test_all.py::test_get_by_id --alluredir allure-results
        continue-on-error: true

      # 6️⃣ Подготовка истории для агрегированного отчёта
      - name: Merge current results into history
        run: |
          mkdir -p gh_pages/allure-history/hi_
